### ISSUE TITLE
Log symfony 404

### ISSUE THREAD

**Issue by Atlanta** [remotelabz/remotelabz#463]
In GitLab by @fnolot on Jul 9, 2020, 13:06

Delete all 404 error in symfony log but we have to keep the 404 error message in the apache log

**Comment by Atlanta** [comment]
In GitLab by @fnolot on Jul 9, 2020, 17:34

created branch [`463-log-symfony-404`](/crestic/remotelabz/-/compare/master...463-log-symfony-404) to address this issue

**Comment by Atlanta** [comment]
In GitLab by @fnolot on Jul 9, 2020, 18:25

assigned to @fnolot and unassigned @Atlanta

**Comment by Atlanta** [comment]
In GitLab by @fnolot on Jul 10, 2020, 15:39

The modifications don't work, even when we clear the cache. 
 ```
       main:
            type: fingers_crossed
#           action_level: error
            handler: nested
            excluded_http_codes: [ 403,404 ]
```
